### ISSUE TITLE
TypeError: Cannot read property '_id' of null

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1028]
https://sentry.data.gouv.fr/betagouvfr/front/issues/1887280/

```
TypeError: Cannot read property '_id' of null
  at bn.initOperatorFormValue (/15-es2015.834cbec4ce0b66d4139d.js:1:141597)
  at u._next (/15-es2015.834cbec4ce0b66d4139d.js:1:140377)
  at u.__tryOrUnsub (/main-es2015.7e83c11ad92bcf7dd225.js:1:100523)
  at u.next (/main-es2015.7e83c11ad92bcf7dd225.js:1:99744)
  at c._next (/main-es2015.7e83c11ad92bcf7dd225.js:1:98896)
...
(45 additional frame(s) were not displayed)
```

**Comment by jonathanfallon** [comment]
fixé mais il en reste dans la liste des territoires @gillesboisson
