### ISSUE TITLE
Bug python dans anomalycheck

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#2726]
```
 Traceback (most recent call last):                                                                                                    │
│ processing carpools between 2024-12-08 12:00:02.608360 and 2024-12-09 12:00:02.608373                                                 │
│   File "/usr/src/distance_duration_anomalycheck.py", line 129, in <module>                                                            │
│     less_than_300_meters_mask = (df_only_class_c_trip.distance < 300) | (df_only_class_c_trip.osrm_distance < 300)                    │
│                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                           │
│   File "/usr/local/lib/python3.11/site-packages/pandas/core/generic.py", line 6299, in __getattr__                                    │
│     return object.__getattribute__(self, name)                                                                                        │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                        │
│ AttributeError: 'DataFrame' object has no attribute 'osrm_distance'                                                                   │
```

**Comment by P3rceval** [comment]
Le bug a été temporaire et que sur l'environnement de démo. A priori OSRM n'a plus été accessible pour le job anomaly_check de démo il y a 41h-47h.

Je ferme le ticket
