### ISSUE TITLE
Normalisation géo

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#477]
Branche: `dev`
Contexte: Worker

### Problème

La normalisation sans lat/lon ne fonctionne pas du tout.

### Infos

Erreur : `Cannot read property 'lon' of undefined`
Stack :
```
TypeError: Cannot read property 'lon' of undefined
    at NormalizationGeoAction.<anonymous> (/code/services/normalization/dist/actions/NormalizationGeoAction.js:58:31)
    at Generator.next (<anonymous>)
    at /code/services/normalization/dist/actions/NormalizationGeoAction.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/code/services/normalization/dist/actions/NormalizationGeoAction.js:13:12)
    at NormalizationGeoAction.findTown (/code/services/normalization/dist/actions/NormalizationGeoAction.js:56:16)
    at NormalizationGeoAction.<anonymous> (/code/services/normalization/dist/actions/NormalizationGeoAction.js:47:61)
    at Generator.next (<anonymous>)
    at fulfilled (/code/services/normalization/dist/actions/NormalizationGeoAction.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Payload:
```json
{
  "method": "normalization:geo",
  "jsonrpc": "2.0",
  "id": null,
  "params": {
    "params": {
      "_id": "5da...",
      "journey_id": "1234",
      "operator_class": "A",
      "operator_id": "5d1...",
      "passenger": {
        "distance": 0,
        "duration": 0,
        "contribution": 300,
        "revenue": 0,
        "expense": 0,
        "incentives": [],
        "payments": [],
        "identity": {
          "phone": "+33612345678",
          "over_18": null
        },
        "start": {
          "datetime": "2019-10-16T22:11:44.754Z",
          "literal": "Paris"
        },
        "end": {
          "datetime": "2019-10-16T22:11:45.754Z",
          "literal": "Evry"
        },
        "seats": 1,
        "is_driver": false
      },
      "created_at": "2019-10-16T22:11:46.274Z"
    },
    "_context": {
      "channel": {
        "service": "acquisition"
      },
      "call": {
        "user": {}
      }
    }
  }
}
```

**Comment by nmrgt** [comment]
De manière général, ce service doit être réécrit.

**Comment by jonathanfallon** [comment]
Service OP à tester avec les données de prod pour validation de tous les payloads disponibles.
